#pragma once
#include <pqxx/pqxx>

namespace odoo::modules::base {

// Seed all world countries and states.
// Safe to run on every boot: ON CONFLICT DO NOTHING skips existing rows.
inline void seedWorldData_(pqxx::work& txn) {

    // Ensure sequence is beyond any manually-inserted IDs
    txn.exec("SELECT setval('res_country_id_seq', (SELECT MAX(id) FROM res_country), true)");

    // ── Countries (250) ────────────────────────────────────────────────────────
    txn.exec(R"SQL(
        INSERT INTO res_country (name, code, phone_code) VALUES
        ('Afghanistan','AF',93),('Åland Islands','AX',358),('Albania','AL',355),
        ('Algeria','DZ',213),('American Samoa','AS',1),('Andorra','AD',376),
        ('Angola','AO',244),('Anguilla','AI',1),('Antarctica','AQ',NULL),
        ('Antigua and Barbuda','AG',1),('Argentina','AR',54),('Armenia','AM',374),
        ('Aruba','AW',297),('Australia','AU',61),('Austria','AT',43),
        ('Azerbaijan','AZ',994),('Bahamas','BS',1),('Bahrain','BH',973),
        ('Bangladesh','BD',880),('Barbados','BB',1),('Belarus','BY',375),
        ('Belgium','BE',32),('Belize','BZ',501),('Benin','BJ',229),
        ('Bermuda','BM',1),('Bhutan','BT',975),('Bolivia','BO',591),
        ('Bosnia and Herzegovina','BA',387),('Botswana','BW',267),
        ('Bouvet Island','BV',47),('Brazil','BR',55),
        ('British Indian Ocean Territory','IO',246),('British Virgin Islands','VG',1),
        ('Brunei','BN',673),('Bulgaria','BG',359),('Burkina Faso','BF',226),
        ('Burundi','BI',257),('Cambodia','KH',855),('Cameroon','CM',237),
        ('Canada','CA',1),('Cape Verde','CV',238),('Caribbean Netherlands','BQ',599),
        ('Cayman Islands','KY',1),('Central African Republic','CF',236),
        ('Chad','TD',235),('Chile','CL',56),('China','CN',86),
        ('Christmas Island','CX',61),('Cocos (Keeling) Islands','CC',61),
        ('Colombia','CO',57),('Comoros','KM',269),('Cook Islands','CK',682),
        ('Costa Rica','CR',506),('Croatia','HR',385),('Cuba','CU',53),
        ('Curaçao','CW',599),('Cyprus','CY',357),('Czechia','CZ',420),
        ('Denmark','DK',45),('Djibouti','DJ',253),('Dominica','DM',1),
        ('Dominican Republic','DO',1),('DR Congo','CD',243),('Ecuador','EC',593),
        ('Egypt','EG',20),('El Salvador','SV',503),('Equatorial Guinea','GQ',240),
        ('Eritrea','ER',291),('Eswatini','SZ',268),('Estonia','EE',372),
        ('Ethiopia','ET',251),('Falkland Islands','FK',500),('Faroe Islands','FO',298),
        ('Fiji','FJ',679),('Finland','FI',358),('France','FR',33),
        ('French Guiana','GF',594),('French Polynesia','PF',689),
        ('French Southern and Antarctic Lands','TF',262),('Gabon','GA',241),
        ('Gambia','GM',220),('Georgia','GE',995),('Germany','DE',49),
        ('Ghana','GH',233),('Gibraltar','GI',350),('Greece','GR',30),
        ('Greenland','GL',299),('Grenada','GD',1),('Guadeloupe','GP',590),
        ('Guam','GU',1),('Guatemala','GT',502),('Guernsey','GG',44),
        ('Guinea','GN',224),('Guinea-Bissau','GW',245),('Guyana','GY',592),
        ('Haiti','HT',509),('Heard Island and McDonald Islands','HM',NULL),
        ('Honduras','HN',504),('Hong Kong','HK',852),('Hungary','HU',36),
        ('Iceland','IS',354),('India','IN',91),('Indonesia','ID',62),
        ('Iran','IR',98),('Iraq','IQ',964),('Ireland','IE',353),
        ('Isle of Man','IM',44),('Israel','IL',972),('Italy','IT',39),
        ('Ivory Coast','CI',225),('Jamaica','JM',1),('Japan','JP',81),
        ('Jersey','JE',44),('Jordan','JO',962),('Kazakhstan','KZ',76),
        ('Kenya','KE',254),('Kiribati','KI',686),('Kosovo','XK',383),
        ('Kuwait','KW',965),('Kyrgyzstan','KG',996),('Laos','LA',856),
        ('Latvia','LV',371),('Lebanon','LB',961),('Lesotho','LS',266),
        ('Liberia','LR',231),('Libya','LY',218),('Liechtenstein','LI',423),
        ('Lithuania','LT',370),('Luxembourg','LU',352),('Macau','MO',853),
        ('Madagascar','MG',261),('Malawi','MW',265),('Malaysia','MY',60),
        ('Maldives','MV',960),('Mali','ML',223),('Malta','MT',356),
        ('Marshall Islands','MH',692),('Martinique','MQ',596),
        ('Mauritania','MR',222),('Mauritius','MU',230),('Mayotte','YT',262),
        ('Mexico','MX',52),('Micronesia','FM',691),('Moldova','MD',373),
        ('Monaco','MC',377),('Mongolia','MN',976),('Montenegro','ME',382),
        ('Montserrat','MS',1),('Morocco','MA',212),('Mozambique','MZ',258),
        ('Myanmar','MM',95),('Namibia','NA',264),('Nauru','NR',674),
        ('Nepal','NP',977),('Netherlands','NL',31),('New Caledonia','NC',687),
        ('New Zealand','NZ',64),('Nicaragua','NI',505),('Niger','NE',227),
        ('Nigeria','NG',234),('Niue','NU',683),('Norfolk Island','NF',672),
        ('North Korea','KP',850),('North Macedonia','MK',389),
        ('Northern Mariana Islands','MP',1),('Norway','NO',47),('Oman','OM',968),
        ('Pakistan','PK',92),('Palau','PW',680),('Palestine','PS',970),
        ('Panama','PA',507),('Papua New Guinea','PG',675),('Paraguay','PY',595),
        ('Peru','PE',51),('Philippines','PH',63),('Pitcairn Islands','PN',64),
        ('Poland','PL',48),('Portugal','PT',351),('Puerto Rico','PR',1),
        ('Qatar','QA',974),('Republic of the Congo','CG',242),
        ('Réunion','RE',262),('Romania','RO',40),('Russia','RU',7),
        ('Rwanda','RW',250),('Saint Barthélemy','BL',590),
        ('Saint Helena, Ascension and Tristan da Cunha','SH',290),
        ('Saint Kitts and Nevis','KN',1),('Saint Lucia','LC',1),
        ('Saint Martin','MF',590),('Saint Pierre and Miquelon','PM',508),
        ('Saint Vincent and the Grenadines','VC',1),('Samoa','WS',685),
        ('San Marino','SM',378),('São Tomé and Príncipe','ST',239),
        ('Saudi Arabia','SA',966),('Senegal','SN',221),('Serbia','RS',381),
        ('Seychelles','SC',248),('Sierra Leone','SL',232),('Singapore','SG',65),
        ('Sint Maarten','SX',1),('Slovakia','SK',421),('Slovenia','SI',386),
        ('Solomon Islands','SB',677),('Somalia','SO',252),('South Africa','ZA',27),
        ('South Georgia','GS',500),('South Korea','KR',82),('South Sudan','SS',211),
        ('Spain','ES',34),('Sri Lanka','LK',94),('Sudan','SD',249),
        ('Suriname','SR',597),('Svalbard and Jan Mayen','SJ',47),('Sweden','SE',46),
        ('Switzerland','CH',41),('Syria','SY',963),('Taiwan','TW',886),
        ('Tajikistan','TJ',992),('Tanzania','TZ',255),('Thailand','TH',66),
        ('Timor-Leste','TL',670),('Togo','TG',228),('Tokelau','TK',690),
        ('Tonga','TO',676),('Trinidad and Tobago','TT',1),('Tunisia','TN',216),
        ('Turkey','TR',90),('Turkmenistan','TM',993),
        ('Turks and Caicos Islands','TC',1),('Tuvalu','TV',688),
        ('Uganda','UG',256),('Ukraine','UA',380),('United Arab Emirates','AE',971),
        ('United Kingdom','GB',44),('United States','US',1),
        ('United States Minor Outlying Islands','UM',268),
        ('United States Virgin Islands','VI',1),('Uruguay','UY',598),
        ('Uzbekistan','UZ',998),('Vanuatu','VU',678),('Vatican City','VA',3906),
        ('Venezuela','VE',58),('Vietnam','VN',84),('Wallis and Futuna','WF',681),
        ('Western Sahara','EH',212),('Yemen','YE',967),('Zambia','ZM',260),
        ('Zimbabwe','ZW',263)
        ON CONFLICT (code) DO NOTHING
    )SQL");

    // ── States/Provinces — single INSERT via JOIN on country code ──────────────
    // Skips rows where (country_id, code) already exists.
    txn.exec(R"SQL(
        INSERT INTO res_country_state (country_id, name, code)
        SELECT c.id, d.sname, d.scode
        FROM (VALUES
          ('MY','Johor','JHR'),('MY','Kedah','KDH'),('MY','Kelantan','KTN'),
          ('MY','Kuala Lumpur','KUL'),('MY','Labuan','LBN'),('MY','Malacca','MLK'),
          ('MY','Negeri Sembilan','NSN'),('MY','Pahang','PHG'),('MY','Penang','PNG'),
          ('MY','Perak','PRK'),('MY','Perlis','PLS'),('MY','Putrajaya','PJY'),
          ('MY','Sabah','SBH'),('MY','Sarawak','SWK'),('MY','Selangor','SGR'),
          ('MY','Terengganu','TRG'),
          ('US','Alabama','AL'),('US','Alaska','AK'),('US','Arizona','AZ'),
          ('US','Arkansas','AR'),('US','California','CA'),('US','Colorado','CO'),
          ('US','Connecticut','CT'),('US','Delaware','DE'),
          ('US','Washington D.C.','DC'),('US','Florida','FL'),('US','Georgia','GA'),
          ('US','Hawaii','HI'),('US','Idaho','ID'),('US','Illinois','IL'),
          ('US','Indiana','IN'),('US','Iowa','IA'),('US','Kansas','KS'),
          ('US','Kentucky','KY'),('US','Louisiana','LA'),('US','Maine','ME'),
          ('US','Maryland','MD'),('US','Massachusetts','MA'),('US','Michigan','MI'),
          ('US','Minnesota','MN'),('US','Mississippi','MS'),('US','Missouri','MO'),
          ('US','Montana','MT'),('US','Nebraska','NE'),('US','Nevada','NV'),
          ('US','New Hampshire','NH'),('US','New Jersey','NJ'),
          ('US','New Mexico','NM'),('US','New York','NY'),
          ('US','North Carolina','NC'),('US','North Dakota','ND'),('US','Ohio','OH'),
          ('US','Oklahoma','OK'),('US','Oregon','OR'),('US','Pennsylvania','PA'),
          ('US','Rhode Island','RI'),('US','South Carolina','SC'),
          ('US','South Dakota','SD'),('US','Tennessee','TN'),('US','Texas','TX'),
          ('US','Utah','UT'),('US','Vermont','VT'),('US','Virginia','VA'),
          ('US','Washington','WA'),('US','West Virginia','WV'),
          ('US','Wisconsin','WI'),('US','Wyoming','WY'),
          ('CA','Alberta','AB'),('CA','British Columbia','BC'),
          ('CA','Manitoba','MB'),('CA','New Brunswick','NB'),
          ('CA','Newfoundland and Labrador','NL'),('CA','Northwest Territories','NT'),
          ('CA','Nova Scotia','NS'),('CA','Nunavut','NU'),('CA','Ontario','ON'),
          ('CA','Prince Edward Island','PE'),('CA','Quebec','QC'),
          ('CA','Saskatchewan','SK'),('CA','Yukon','YT'),
          ('GB','England','ENG'),('GB','Northern Ireland','NIR'),
          ('GB','Scotland','SCT'),('GB','Wales','WLS'),
          ('AU','Australian Capital Territory','ACT'),
          ('AU','New South Wales','NSW'),('AU','Northern Territory','NT'),
          ('AU','Queensland','QLD'),('AU','South Australia','SA'),
          ('AU','Tasmania','TAS'),('AU','Victoria','VIC'),
          ('AU','Western Australia','WA'),
          ('DE','Baden-Württemberg','BW'),('DE','Bavaria','BY'),
          ('DE','Berlin','BE'),('DE','Brandenburg','BB'),('DE','Bremen','HB'),
          ('DE','Hamburg','HH'),('DE','Hesse','HE'),('DE','Lower Saxony','NI'),
          ('DE','Mecklenburg-Vorpommern','MV'),('DE','North Rhine-Westphalia','NW'),
          ('DE','Rhineland-Palatinate','RP'),('DE','Saarland','SL'),
          ('DE','Saxony','SN'),('DE','Saxony-Anhalt','ST'),
          ('DE','Schleswig-Holstein','SH'),('DE','Thuringia','TH'),
          ('FR','Auvergne-Rhône-Alpes','ARA'),('FR','Bourgogne-Franche-Comté','BFC'),
          ('FR','Bretagne','BRE'),('FR','Centre-Val de Loire','CVL'),
          ('FR','Corse','COR'),('FR','Grand Est','GES'),('FR','Guadeloupe','GP'),
          ('FR','Guyane','GF'),('FR','Hauts-de-France','HDF'),
          ('FR','Île-de-France','IDF'),('FR','La Réunion','RE'),
          ('FR','Martinique','MQ'),('FR','Mayotte','YT'),('FR','Normandie','NOR'),
          ('FR','Nouvelle-Aquitaine','NAQ'),('FR','Occitanie','OCC'),
          ('FR','Pays de la Loire','PDL'),
          ('FR','Provence-Alpes-Côte d''Azur','PAC'),
          ('IN','Andaman and Nicobar Islands','AN'),('IN','Andhra Pradesh','AP'),
          ('IN','Arunachal Pradesh','AR'),('IN','Assam','AS'),('IN','Bihar','BR'),
          ('IN','Chandigarh','CH'),('IN','Chhattisgarh','CG'),
          ('IN','Dadra and Nagar Haveli and Daman and Diu','DD'),
          ('IN','Delhi','DL'),('IN','Goa','GA'),('IN','Gujarat','GJ'),
          ('IN','Haryana','HR'),('IN','Himachal Pradesh','HP'),
          ('IN','Jammu and Kashmir','JK'),('IN','Jharkhand','JH'),
          ('IN','Karnataka','KA'),('IN','Kerala','KL'),('IN','Ladakh','LA'),
          ('IN','Lakshadweep','LD'),('IN','Madhya Pradesh','MP'),
          ('IN','Maharashtra','MH'),('IN','Manipur','MN'),('IN','Meghalaya','ML'),
          ('IN','Mizoram','MZ'),('IN','Nagaland','NL'),('IN','Odisha','OR'),
          ('IN','Puducherry','PY'),('IN','Punjab','PB'),('IN','Rajasthan','RJ'),
          ('IN','Sikkim','SK'),('IN','Tamil Nadu','TN'),('IN','Telangana','TS'),
          ('IN','Tripura','TR'),('IN','Uttar Pradesh','UP'),
          ('IN','Uttarakhand','UK'),('IN','West Bengal','WB'),
          ('JP','Aichi','JP-23'),('JP','Akita','JP-05'),('JP','Aomori','JP-02'),
          ('JP','Chiba','JP-12'),('JP','Ehime','JP-38'),('JP','Fukui','JP-18'),
          ('JP','Fukuoka','JP-40'),('JP','Fukushima','JP-07'),('JP','Gifu','JP-21'),
          ('JP','Gunma','JP-10'),('JP','Hiroshima','JP-34'),
          ('JP','Hokkaido','JP-01'),('JP','Hyogo','JP-28'),('JP','Ibaraki','JP-08'),
          ('JP','Ishikawa','JP-17'),('JP','Iwate','JP-03'),('JP','Kagawa','JP-37'),
          ('JP','Kagoshima','JP-46'),('JP','Kanagawa','JP-14'),
          ('JP','Kochi','JP-39'),('JP','Kumamoto','JP-43'),('JP','Kyoto','JP-26'),
          ('JP','Mie','JP-24'),('JP','Miyagi','JP-04'),('JP','Miyazaki','JP-45'),
          ('JP','Nagano','JP-20'),('JP','Nagasaki','JP-42'),('JP','Nara','JP-29'),
          ('JP','Niigata','JP-15'),('JP','Oita','JP-44'),('JP','Okayama','JP-33'),
          ('JP','Okinawa','JP-47'),('JP','Osaka','JP-27'),('JP','Saga','JP-41'),
          ('JP','Saitama','JP-11'),('JP','Shiga','JP-25'),('JP','Shimane','JP-32'),
          ('JP','Shizuoka','JP-22'),('JP','Tochigi','JP-09'),
          ('JP','Tokushima','JP-36'),('JP','Tokyo','JP-13'),
          ('JP','Tottori','JP-31'),('JP','Toyama','JP-16'),
          ('JP','Wakayama','JP-30'),('JP','Yamagata','JP-06'),
          ('JP','Yamaguchi','JP-35'),('JP','Yamanashi','JP-19'),
          ('CN','Anhui','AH'),('CN','Beijing','BJ'),('CN','Chongqing','CQ'),
          ('CN','Fujian','FJ'),('CN','Gansu','GS'),('CN','Guangdong','GD'),
          ('CN','Guangxi','GX'),('CN','Guizhou','GZ'),('CN','Hainan','HI'),
          ('CN','Hebei','HE'),('CN','Heilongjiang','HL'),('CN','Henan','HA'),
          ('CN','Hong Kong SAR','HK'),('CN','Hubei','HB'),('CN','Hunan','HN'),
          ('CN','Inner Mongolia','NM'),('CN','Jiangsu','JS'),('CN','Jiangxi','JX'),
          ('CN','Jilin','JL'),('CN','Liaoning','LN'),('CN','Macau SAR','MO'),
          ('CN','Ningxia','NX'),('CN','Qinghai','QH'),('CN','Shaanxi','SN'),
          ('CN','Shandong','SD'),('CN','Shanghai','SH'),('CN','Shanxi','SX'),
          ('CN','Sichuan','SC'),('CN','Tianjin','TJ'),('CN','Tibet','XZ'),
          ('CN','Xinjiang','XJ'),('CN','Yunnan','YN'),('CN','Zhejiang','ZJ'),
          ('ID','Aceh','AC'),('ID','Bali','BA'),('ID','Banten','BT'),
          ('ID','Bengkulu','BE'),('ID','DI Yogyakarta','YO'),
          ('ID','DKI Jakarta','JK'),('ID','Gorontalo','GO'),('ID','Jambi','JA'),
          ('ID','Jawa Barat','JB'),('ID','Jawa Tengah','JT'),
          ('ID','Jawa Timur','JI'),('ID','Kalimantan Barat','KB'),
          ('ID','Kalimantan Selatan','KS'),('ID','Kalimantan Tengah','KT'),
          ('ID','Kalimantan Timur','KI'),('ID','Kalimantan Utara','KU'),
          ('ID','Kepulauan Bangka Belitung','BB'),('ID','Kepulauan Riau','KR'),
          ('ID','Lampung','LA'),('ID','Maluku','MA'),('ID','Maluku Utara','MU'),
          ('ID','Nusa Tenggara Barat','NB'),('ID','Nusa Tenggara Timur','NT'),
          ('ID','Papua','PA'),('ID','Papua Barat','PB'),
          ('ID','Papua Barat Daya','PD'),('ID','Papua Pegunungan','PE'),
          ('ID','Papua Selatan','PS'),('ID','Papua Tengah','PT'),('ID','Riau','RI'),
          ('ID','Sulawesi Barat','SR'),('ID','Sulawesi Selatan','SN2'),
          ('ID','Sulawesi Tengah','ST'),('ID','Sulawesi Tenggara','SG'),
          ('ID','Sulawesi Utara','SA'),('ID','Sumatera Barat','SB'),
          ('ID','Sumatera Selatan','SS'),('ID','Sumatera Utara','SU'),
          ('BR','Acre','AC'),('BR','Alagoas','AL'),('BR','Amapá','AP'),
          ('BR','Amazonas','AM'),('BR','Bahia','BA'),('BR','Ceará','CE'),
          ('BR','Distrito Federal','DF'),('BR','Espírito Santo','ES'),
          ('BR','Goiás','GO'),('BR','Maranhão','MA'),('BR','Mato Grosso','MT'),
          ('BR','Mato Grosso do Sul','MS'),('BR','Minas Gerais','MG'),
          ('BR','Pará','PA'),('BR','Paraíba','PB'),('BR','Paraná','PR'),
          ('BR','Pernambuco','PE'),('BR','Piauí','PI'),
          ('BR','Rio de Janeiro','RJ'),('BR','Rio Grande do Norte','RN'),
          ('BR','Rio Grande do Sul','RS'),('BR','Rondônia','RO'),
          ('BR','Roraima','RR'),('BR','Santa Catarina','SC'),
          ('BR','São Paulo','SP'),('BR','Sergipe','SE'),('BR','Tocantins','TO'),
          ('MX','Aguascalientes','AG'),('MX','Baja California','BC'),
          ('MX','Baja California Sur','BS'),('MX','Campeche','CM'),
          ('MX','Chiapas','CS'),('MX','Chihuahua','CH'),
          ('MX','Ciudad de México','CMX'),('MX','Coahuila','CO'),
          ('MX','Colima','CL'),('MX','Durango','DG'),
          ('MX','Estado de México','EM'),('MX','Guanajuato','GT'),
          ('MX','Guerrero','GR'),('MX','Hidalgo','HG'),('MX','Jalisco','JA'),
          ('MX','Michoacán','MI'),('MX','Morelos','MO'),('MX','Nayarit','NA'),
          ('MX','Nuevo León','NL'),('MX','Oaxaca','OA'),('MX','Puebla','PU'),
          ('MX','Querétaro','QT'),('MX','Quintana Roo','QR'),
          ('MX','San Luis Potosí','SL'),('MX','Sinaloa','SI'),
          ('MX','Sonora','SO'),('MX','Tabasco','TB'),('MX','Tamaulipas','TM'),
          ('MX','Tlaxcala','TL'),('MX','Veracruz','VE'),('MX','Yucatán','YU'),
          ('MX','Zacatecas','ZA'),
          ('ZA','Eastern Cape','EC'),('ZA','Free State','FS'),
          ('ZA','Gauteng','GP'),('ZA','KwaZulu-Natal','KZN'),
          ('ZA','Limpopo','LP'),('ZA','Mpumalanga','MP'),
          ('ZA','North West','NW'),('ZA','Northern Cape','NC'),
          ('ZA','Western Cape','WC'),
          ('AE','Abu Dhabi','AZ'),('AE','Ajman','AJ'),('AE','Dubai','DU'),
          ('AE','Fujairah','FU'),('AE','Ras Al Khaimah','RK'),
          ('AE','Sharjah','SH'),('AE','Umm Al Quwain','UQ'),
          ('SA','Al Bahah','BA'),('SA','Al Hudud ash Shamaliyah','HS'),
          ('SA','Al Jawf','JF'),('SA','Al Madinah','MD'),
          ('SA','Al Qasim','QS'),('SA','Ar Riyad','RD'),('SA','Asir','AS'),
          ('SA','Eastern Province','EP'),('SA','Ha''il','HA'),
          ('SA','Jazan','JZ'),('SA','Makkah','MK'),('SA','Najran','NJ'),
          ('SA','Tabuk','TB'),
          ('SG','Central Singapore','CS'),('SG','North East','NE'),
          ('SG','North West','NW'),('SG','South East','SE'),
          ('SG','South West','SW'),
          ('NZ','Auckland','AUK'),('NZ','Bay of Plenty','BOP'),
          ('NZ','Canterbury','CAN'),('NZ','Gisborne','GIS'),
          ('NZ','Hawke''s Bay','HKB'),('NZ','Manawatu-Whanganui','MWT'),
          ('NZ','Marlborough','MBH'),('NZ','Nelson','NSN'),
          ('NZ','Northland','NTL'),('NZ','Otago','OTA'),
          ('NZ','Southland','STL'),('NZ','Taranaki','TKI'),
          ('NZ','Tasman','TAS'),('NZ','Waikato','WKO'),
          ('NZ','Wellington','WGN'),('NZ','West Coast','WTC'),
          ('NL','Drenthe','DR'),('NL','Flevoland','FL'),('NL','Friesland','FR'),
          ('NL','Gelderland','GE'),('NL','Groningen','GR'),('NL','Limburg','LI'),
          ('NL','North Brabant','NB'),('NL','North Holland','NH'),
          ('NL','Overijssel','OV'),('NL','South Holland','ZH'),
          ('NL','Utrecht','UT'),('NL','Zeeland','ZE'),
          ('BE','Antwerp','VAN'),('BE','Brussels','BRU'),
          ('BE','East Flanders','VOV'),('BE','Flemish Brabant','VBR'),
          ('BE','Hainaut','WHT'),('BE','Liège','WLG'),('BE','Limburg','VLI'),
          ('BE','Luxembourg','WLX'),('BE','Namur','WNA'),
          ('BE','Walloon Brabant','WBR'),('BE','West Flanders','VWV'),
          ('CH','Aargau','AG'),('CH','Appenzell Ausserrhoden','AR'),
          ('CH','Appenzell Innerrhoden','AI'),('CH','Basel-Landschaft','BL'),
          ('CH','Basel-Stadt','BS'),('CH','Bern','BE'),('CH','Fribourg','FR'),
          ('CH','Geneva','GE'),('CH','Glarus','GL'),('CH','Graubünden','GR'),
          ('CH','Jura','JU'),('CH','Lucerne','LU'),('CH','Neuchâtel','NE'),
          ('CH','Nidwalden','NW'),('CH','Obwalden','OW'),
          ('CH','Schaffhausen','SH'),('CH','Schwyz','SZ'),
          ('CH','Solothurn','SO'),('CH','St. Gallen','SG'),
          ('CH','Thurgau','TG'),('CH','Ticino','TI'),('CH','Uri','UR'),
          ('CH','Valais','VS'),('CH','Vaud','VD'),('CH','Zug','ZG'),
          ('CH','Zürich','ZH'),
          ('ES','Andalusia','AN'),('ES','Aragon','AR'),('ES','Asturias','AS'),
          ('ES','Balearic Islands','IB'),('ES','Basque Country','PV'),
          ('ES','Canary Islands','CN'),('ES','Cantabria','CB'),
          ('ES','Castilla-La Mancha','CM'),('ES','Castilla y León','CL'),
          ('ES','Catalonia','CT'),('ES','Ceuta','CE'),
          ('ES','Extremadura','EX'),('ES','Galicia','GA'),
          ('ES','La Rioja','RI'),('ES','Madrid','MD'),('ES','Melilla','ML'),
          ('ES','Murcia','MC'),('ES','Navarre','NC'),('ES','Valencia','VC'),
          ('IT','Abruzzo','ABR'),('IT','Aosta Valley','VDA'),
          ('IT','Apulia','PUG'),('IT','Basilicata','BAS'),
          ('IT','Calabria','CAL'),('IT','Campania','CAM'),
          ('IT','Emilia-Romagna','EMR'),('IT','Friuli-Venezia Giulia','FVG'),
          ('IT','Lazio','LAZ'),('IT','Liguria','LIG'),('IT','Lombardy','LOM'),
          ('IT','Marche','MAR'),('IT','Molise','MOL'),('IT','Piedmont','PIE'),
          ('IT','Sardinia','SAR'),('IT','Sicily','SIC'),
          ('IT','Trentino-South Tyrol','TAA'),('IT','Tuscany','TOS'),
          ('IT','Umbria','UMB'),('IT','Veneto','VEN'),
          ('NG','Abia','AB'),('NG','Adamawa','AD'),('NG','Akwa Ibom','AK'),
          ('NG','Anambra','AN'),('NG','Bauchi','BA'),('NG','Bayelsa','BY'),
          ('NG','Benue','BE'),('NG','Borno','BO'),('NG','Cross River','CR'),
          ('NG','Delta','DE'),('NG','Ebonyi','EB'),('NG','Edo','ED'),
          ('NG','Ekiti','EK'),('NG','Enugu','EN'),('NG','FCT Abuja','FC'),
          ('NG','Gombe','GO'),('NG','Imo','IM'),('NG','Jigawa','JI'),
          ('NG','Kaduna','KD'),('NG','Kano','KN'),('NG','Katsina','KT'),
          ('NG','Kebbi','KE'),('NG','Kogi','KO'),('NG','Kwara','KW'),
          ('NG','Lagos','LA'),('NG','Nasarawa','NA'),('NG','Niger','NI'),
          ('NG','Ogun','OG'),('NG','Ondo','ON'),('NG','Osun','OS'),
          ('NG','Oyo','OY'),('NG','Plateau','PL'),('NG','Rivers','RI'),
          ('NG','Sokoto','SO'),('NG','Taraba','TA'),('NG','Yobe','YO'),
          ('NG','Zamfara','ZA'),
          ('EG','Alexandria','ALX'),('EG','Aswan','ASN'),('EG','Asyut','AST'),
          ('EG','Beheira','BH'),('EG','Beni Suef','BNS'),('EG','Cairo','C'),
          ('EG','Dakahlia','DK'),('EG','Damietta','DT'),('EG','Fayyum','FYM'),
          ('EG','Gharbia','GH'),('EG','Giza','GZ'),('EG','Ismailia','IS'),
          ('EG','Kafr el-Sheikh','KFS'),('EG','Luxor','LX'),
          ('EG','Matrouh','MT'),('EG','Minya','MN'),('EG','Monufia','MNF'),
          ('EG','New Valley','WAD'),('EG','North Sinai','SIN'),
          ('EG','Port Said','PTS'),('EG','Qalyubia','KB'),('EG','Qena','KN2'),
          ('EG','Red Sea','BA'),('EG','Sharqia','SHR'),('EG','Sohag','SHG'),
          ('EG','South Sinai','JS'),('EG','Suez','SUZ'),
          ('PK','Azad Kashmir','AJK'),('PK','Balochistan','BA'),
          ('PK','Gilgit-Baltistan','GB'),
          ('PK','Islamabad Capital Territory','IS'),
          ('PK','Khyber Pakhtunkhwa','KP'),('PK','Punjab','PB'),
          ('PK','Sindh','SD'),
          ('BD','Barisal','A'),('BD','Chittagong','B'),('BD','Dhaka','C'),
          ('BD','Khulna','D'),('BD','Mymensingh','H'),('BD','Rajshahi','E'),
          ('BD','Rangpur','F'),('BD','Sylhet','G'),
          ('TH','Amnat Charoen','AM'),('TH','Ang Thong','AN'),
          ('TH','Bangkok','BM'),('TH','Bueng Kan','BK'),('TH','Buri Ram','BR'),
          ('TH','Chachoengsao','CC'),('TH','Chai Nat','CN'),
          ('TH','Chaiyaphum','CP'),('TH','Chanthaburi','CT'),
          ('TH','Chiang Mai','CM'),('TH','Chiang Rai','CR'),
          ('TH','Chon Buri','CB'),('TH','Chumphon','CPN'),
          ('TH','Kalasin','KS'),('TH','Kamphaeng Phet','KP2'),
          ('TH','Kanchanaburi','KN'),('TH','Khon Kaen','KK'),
          ('TH','Krabi','KR'),('TH','Lampang','LP'),('TH','Lamphun','LN'),
          ('TH','Loei','LE'),('TH','Lop Buri','LB'),('TH','Mae Hong Son','MH'),
          ('TH','Maha Sarakham','MK'),('TH','Mukdahan','MD'),
          ('TH','Nakhon Nayok','NY'),('TH','Nakhon Pathom','PTO'),
          ('TH','Nakhon Phanom','NP'),('TH','Nakhon Ratchasima','NM'),
          ('TH','Nakhon Sawan','NW'),('TH','Nakhon Si Thammarat','NT'),
          ('TH','Nan','NA'),('TH','Narathiwat','NR'),
          ('TH','Nong Bua Lam Phu','NL'),('TH','Nong Khai','NK'),
          ('TH','Nonthaburi','NB'),('TH','Pathum Thani','PT'),
          ('TH','Pattani','PN'),('TH','Phang Nga','PNA'),
          ('TH','Phatthalung','PL'),('TH','Phayao','PY'),
          ('TH','Phetchabun','PB'),('TH','Phetchaburi','PE'),
          ('TH','Phichit','PII'),('TH','Phitsanulok','PL2'),
          ('TH','Phra Nakhon Si Ayutthaya','AY'),('TH','Phrae','PR'),
          ('TH','Phuket','PK'),('TH','Prachin Buri','PRI'),
          ('TH','Prachuap Khiri Khan','PKN'),('TH','Ranong','RN'),
          ('TH','Ratchaburi','RB'),('TH','Rayong','RY'),('TH','Roi Et','RE'),
          ('TH','Sa Kaeo','SK'),('TH','Sakon Nakhon','SN'),
          ('TH','Samut Prakan','SP'),('TH','Samut Sakhon','SS'),
          ('TH','Samut Songkhram','SSK'),('TH','Saraburi','SR'),
          ('TH','Satun','ST'),('TH','Sing Buri','SB'),('TH','Si Sa Ket','SC'),
          ('TH','Songkhla','SO'),('TH','Sukhothai','SU'),
          ('TH','Suphan Buri','SPB'),('TH','Surat Thani','SRT'),
          ('TH','Surin','SR2'),('TH','Tak','TK'),('TH','Trang','TG'),
          ('TH','Trat','TR'),('TH','Ubon Ratchathani','UB'),
          ('TH','Udon Thani','UD'),('TH','Uthai Thani','UT'),
          ('TH','Uttaradit','UT2'),('TH','Yala','YL'),('TH','Yasothon','YS'),
          ('VN','An Giang','AG'),('VN','Bà Rịa-Vũng Tàu','BR'),
          ('VN','Bắc Giang','BG'),('VN','Bắc Kạn','BK'),
          ('VN','Bạc Liêu','BL'),('VN','Bắc Ninh','BN'),
          ('VN','Bến Tre','BT'),('VN','Bình Định','BD'),
          ('VN','Bình Dương','BDG'),('VN','Bình Phước','BP'),
          ('VN','Bình Thuận','BTH'),('VN','Cà Mau','CM'),
          ('VN','Cần Thơ','CT'),('VN','Cao Bằng','CB'),
          ('VN','Đà Nẵng','DN'),('VN','Đắk Lắk','DL'),
          ('VN','Đắk Nông','DNG'),('VN','Điện Biên','DB'),
          ('VN','Đồng Nai','DNI'),('VN','Đồng Tháp','DT'),
          ('VN','Gia Lai','GL'),('VN','Hà Giang','HGI'),
          ('VN','Hà Nam','HN2'),('VN','Hà Nội','HN'),
          ('VN','Hà Tĩnh','HT'),('VN','Hải Dương','HD'),
          ('VN','Hải Phòng','HP'),('VN','Hậu Giang','HGG'),
          ('VN','Hòa Bình','HB'),('VN','Hồ Chí Minh','HC'),
          ('VN','Hưng Yên','HY'),('VN','Khánh Hòa','KH'),
          ('VN','Kiên Giang','KG'),('VN','Kon Tum','KT'),
          ('VN','Lai Châu','LC'),('VN','Lâm Đồng','LD'),
          ('VN','Lạng Sơn','LS'),('VN','Lào Cai','LCI'),
          ('VN','Long An','LA'),('VN','Nam Định','ND'),
          ('VN','Nghệ An','NA'),('VN','Ninh Bình','NB'),
          ('VN','Ninh Thuận','NT'),('VN','Phú Thọ','PT'),
          ('VN','Phú Yên','PY'),('VN','Quảng Bình','QB'),
          ('VN','Quảng Nam','QN'),('VN','Quảng Ngãi','QNG'),
          ('VN','Quảng Ninh','QNI'),('VN','Quảng Trị','QT'),
          ('VN','Sóc Trăng','ST'),('VN','Sơn La','SL'),
          ('VN','Tây Ninh','TN'),('VN','Thái Bình','TB'),
          ('VN','Thái Nguyên','TNG'),('VN','Thanh Hóa','TH'),
          ('VN','Thừa Thiên Huế','TTH'),('VN','Tiền Giang','TG'),
          ('VN','Trà Vinh','TV'),('VN','Tuyên Quang','TQ'),
          ('VN','Vĩnh Long','VL'),('VN','Vĩnh Phúc','VP'),
          ('VN','Yên Bái','YB'),
          ('PH','Abra','ABR'),('PH','Agusan del Norte','AGN'),
          ('PH','Agusan del Sur','AGS'),('PH','Aklan','AKL'),
          ('PH','Albay','ALB'),('PH','Antique','ANT'),('PH','Apayao','APA'),
          ('PH','Aurora','AUR'),('PH','Basilan','BAS'),('PH','Bataan','BAN'),
          ('PH','Batanes','BTN'),('PH','Batangas','BTG'),
          ('PH','Benguet','BEN'),('PH','Biliran','BIL'),('PH','Bohol','BOH'),
          ('PH','Bukidnon','BUK'),('PH','Bulacan','BUL'),
          ('PH','Cagayan','CAG'),('PH','Camarines Norte','CAN'),
          ('PH','Camarines Sur','CAS'),('PH','Camiguin','CAM'),
          ('PH','Capiz','CAP'),('PH','Catanduanes','CAT'),
          ('PH','Cavite','CAV'),('PH','Cebu','CEB'),('PH','Cotabato','NCO'),
          ('PH','Davao del Norte','DAV'),('PH','Davao del Sur','DAS'),
          ('PH','Davao de Oro','COM'),('PH','Davao Occidental','DVO'),
          ('PH','Davao Oriental','DAO'),('PH','Dinagat Islands','DIN'),
          ('PH','Eastern Samar','EAS'),('PH','Guimaras','GUI'),
          ('PH','Ifugao','IFU'),('PH','Ilocos Norte','ILN'),
          ('PH','Ilocos Sur','ILS'),('PH','Iloilo','ILI'),
          ('PH','Isabela','ISA'),('PH','Kalinga','KAL'),
          ('PH','La Union','LUN'),('PH','Laguna','LAG'),
          ('PH','Lanao del Norte','LAN'),('PH','Lanao del Sur','LAS'),
          ('PH','Leyte','LEY'),('PH','Marinduque','MAD'),
          ('PH','Masbate','MAS'),('PH','Metro Manila','NCR'),
          ('PH','Misamis Occidental','MSC'),('PH','Misamis Oriental','MSR'),
          ('PH','Mountain Province','MOU'),('PH','Negros Occidental','NEC'),
          ('PH','Negros Oriental','NER'),('PH','Northern Samar','NSA'),
          ('PH','Nueva Ecija','NUE'),('PH','Nueva Vizcaya','NUV'),
          ('PH','Occidental Mindoro','MDC'),('PH','Oriental Mindoro','MDR'),
          ('PH','Palawan','PLW'),('PH','Pampanga','PAM'),
          ('PH','Pangasinan','PAN'),('PH','Quezon','QUE'),
          ('PH','Quirino','QUI'),('PH','Rizal','RIZ'),('PH','Romblon','ROM'),
          ('PH','Samar','WSA'),('PH','Sarangani','SAR'),
          ('PH','Siquijor','SIG'),('PH','Sorsogon','SOR'),
          ('PH','South Cotabato','SCO'),('PH','Southern Leyte','SLE'),
          ('PH','Sultan Kudarat','SUK'),('PH','Sulu','SLU'),
          ('PH','Surigao del Norte','SUN'),('PH','Surigao del Sur','SUR'),
          ('PH','Tarlac','TAR'),('PH','Tawi-Tawi','TAW'),
          ('PH','Zambales','ZMB'),('PH','Zamboanga del Norte','ZAN'),
          ('PH','Zamboanga del Sur','ZAS'),('PH','Zamboanga Sibugay','ZSI')
        ) AS d(cc, sname, scode)
        JOIN res_country c ON c.code = d.cc
        ON CONFLICT (country_id, code) DO NOTHING
    )SQL");
}

} // namespace odoo::modules::base
