#pragma once
#include <nlohmann/json.hpp>
#include <openssl/rand.h>
#include <algorithm>
#include <chrono>
#include <iomanip>
#include <mutex>
#include <optional>
#include <sstream>
#include <stdexcept>
#include <string>
#include <unordered_map>
#include <vector>

namespace odoo::infrastructure {

// ============================================================
// Session
// ============================================================
/**
 * @brief Represents one authenticated browser session.
 *
 * Mirrors Odoo's ir.http session structure closely enough that
 * the OWL frontend doesn't need changes:
 * @code
 * {
 *   "uid":          7,
 *   "login":        "admin",
 *   "db":           "odoo",
 *   "session_id":   "abc123...",
 *   "context":      { "lang": "en_US", "tz": "UTC" }
 * }
 * @endcode
 */
struct Session {
    std::string    sessionId;
    int            uid         = 0;    ///< res.users id; 0 = anonymous
    std::string    login;              ///< e.g. "admin"
    std::string    db;                 ///< database name
    nlohmann::json context = nlohmann::json::object(); ///< user context

    // Enriched fields populated after authentication
    std::string       name;               ///< display name from res_partner
    int               partnerId  = 0;     ///< res_partner.id
    int               companyId  = 0;     ///< res_company.id
    std::string       companyName;        ///< res_company.name
    bool              isAdmin    = false; ///< member of Administrator group (id=3)
    std::vector<int>  groupIds;           ///< all res_groups ids this user belongs to

    using Clock     = std::chrono::steady_clock;
    using TimePoint = Clock::time_point;

    TimePoint createdAt  = Clock::now();
    TimePoint accessedAt = Clock::now();

    bool isAuthenticated() const { return uid > 0; }

    /// Returns true if the user belongs to the given group id.
    bool hasGroup(int gid) const {
        return std::find(groupIds.begin(), groupIds.end(), gid) != groupIds.end();
    }

    /// Returns true if the user belongs to ANY of the given group ids.
    bool hasAnyGroup(std::initializer_list<int> gids) const {
        for (int gid : gids)
            if (hasGroup(gid)) return true;
        return false;
    }

    nlohmann::json toJson() const {
        nlohmann::json gArr = nlohmann::json::array();
        for (int g : groupIds) gArr.push_back(g);
        return {
            {"session_id",   sessionId},
            {"uid",          uid},
            {"login",        login},
            {"db",           db},
            {"context",      context},
            {"name",         name},
            {"partner_id",   partnerId > 0  ? nlohmann::json(partnerId)  : nlohmann::json(false)},
            {"company_id",   companyId > 0  ? nlohmann::json(companyId)  : nlohmann::json(false)},
            {"company_name", companyName},
            {"is_admin",     isAdmin},
            {"is_system",    isAdmin},
            {"group_ids",    gArr},
        };
    }
};


// ============================================================
// SessionManager
// ============================================================
/**
 * @brief Thread-safe in-memory session store.
 *
 * Sessions are keyed by a 128-bit hex token generated by create().
 * Expired sessions are evicted lazily on get() and explicitly via
 * evictExpired().
 *
 * The session cookie name matches Odoo's default: "session_id".
 *
 * Usage (inside JsonRpcDispatcher):
 * @code
 *   auto sid = request.get_header_value("Cookie");   // parse "session_id=..."
 *   auto session = sessions->get(sid);
 *   if (!session || !session->isAuthenticated())
 *       return jsonRpcError(100, "Session expired");
 * @endcode
 */
class SessionManager {
public:
    using Duration = std::chrono::seconds;

    /**
     * @param ttl  Session lifetime from last access. Default: 1 hour.
     */
    explicit SessionManager(Duration ttl = std::chrono::hours{1})
        : ttl_(ttl) {}

    // ----------------------------------------------------------
    // CRUD
    // ----------------------------------------------------------

    /**
     * @brief Create a new anonymous session and return its id.
     */
    std::string create(const std::string& db = "") {
        Session s;
        s.sessionId = generateId_();
        s.db        = db;

        std::scoped_lock lock{mutex_};
        const std::string id = s.sessionId;
        store_[id] = std::move(s);
        return id;
    }

    /**
     * @brief Look up a session by id.
     *
     * Returns nullopt if the id is unknown or the session has expired.
     * Touching the session resets its TTL.
     */
    std::optional<Session> get(const std::string& sessionId) {
        std::scoped_lock lock{mutex_};
        auto it = store_.find(sessionId);
        if (it == store_.end()) return std::nullopt;

        if (isExpired_(it->second)) {
            store_.erase(it);
            return std::nullopt;
        }

        it->second.accessedAt = Session::Clock::now();
        return it->second;
    }

    /**
     * @brief Update a session's fields in-place.
     * Typically called by AuthService after successful login.
     *
     * @param sessionId  Target session.
     * @param patch      Callable receiving Session& for mutation.
     * @returns          true if session existed and was updated.
     */
    template<typename Fn>
    bool update(const std::string& sessionId, Fn&& patch) {
        std::scoped_lock lock{mutex_};
        auto it = store_.find(sessionId);
        if (it == store_.end() || isExpired_(it->second)) return false;
        patch(it->second);
        it->second.accessedAt = Session::Clock::now();
        return true;
    }

    /**
     * @brief Destroy a session (logout).
     */
    void destroy(const std::string& sessionId) {
        std::scoped_lock lock{mutex_};
        store_.erase(sessionId);
    }

    // ----------------------------------------------------------
    // Maintenance
    // ----------------------------------------------------------

    /**
     * @brief Evict all expired sessions.
     * Call periodically from a background timer or before healthCheck().
     * @returns Number of sessions evicted.
     */
    std::size_t evictExpired() {
        std::scoped_lock lock{mutex_};
        std::size_t count = 0;
        for (auto it = store_.begin(); it != store_.end(); ) {
            if (isExpired_(it->second)) { it = store_.erase(it); ++count; }
            else                        { ++it; }
        }
        return count;
    }

    /** @brief Current number of live sessions (including potentially expired). */
    std::size_t size() const {
        std::scoped_lock lock{mutex_};
        return store_.size();
    }

    nlohmann::json healthInfo() const {
        std::scoped_lock lock{mutex_};
        return {
            {"active_sessions", static_cast<int>(store_.size())},
            {"ttl_seconds",     ttl_.count()},
        };
    }

    // ----------------------------------------------------------
    // Cookie helpers (static)
    // ----------------------------------------------------------

    /** @brief Cookie name Odoo's frontend expects. */
    static constexpr const char* cookieName() { return "session_id"; }

    /**
     * @brief Extract session id from a raw Cookie header value.
     * e.g. "session_id=abc123; other=val" → "abc123"
     */
    static std::string extractFromCookie(const std::string& cookieHeader) {
        const std::string needle = std::string(cookieName()) + "=";
        const auto pos = cookieHeader.find(needle);
        if (pos == std::string::npos) return {};
        const auto start = pos + needle.size();
        const auto end   = cookieHeader.find(';', start);
        return cookieHeader.substr(start,
            end == std::string::npos ? std::string::npos : end - start);
    }

private:
    bool isExpired_(const Session& s) const {
        return (Session::Clock::now() - s.accessedAt) > ttl_;
    }

    static std::string generateId_() {
        // 128-bit cryptographically random hex token via OpenSSL CSPRNG
        unsigned char buf[16];
        if (RAND_bytes(buf, sizeof(buf)) != 1)
            throw std::runtime_error("SessionManager: RAND_bytes failed");
        std::ostringstream ss;
        ss << std::hex << std::setfill('0');
        for (unsigned char b : buf)
            ss << std::setw(2) << static_cast<unsigned>(b);
        return ss.str();
    }

    Duration                              ttl_;
    mutable std::mutex                    mutex_;
    std::unordered_map<std::string, Session> store_;
};

} // namespace odoo::infrastructure